---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pv-labels-operator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pv-labels-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-labels-operator
subjects:
- kind: ServiceAccount
  name: pv-labels-operator
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: pv-labels-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-labels-operator
  namespace: kube-system
  labels:
    app: pv-labels-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pv-labels-operator
  template:
    metadata:
      labels:
        app: pv-labels-operator
    spec:
      serviceAccountName: pv-labels-operator
      containers:
      - name: pv-labels-operator
        image: docker.io/cinaq/pv-labels-operator:0.1.1
        args:
        - --resync-period=60m
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      nodeSelector:
        kubernetes.io/os: linux
